[package]
name = "typing_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
rand = "0.8.4"
async-timer = "1.0.0-beta.1"